Sprint 1 PR
khodya/go-urlshortener pull request #1
Opened 2021-08-28 22:08 UTC by khodya

Completed 3 increments; all tests passed

2021-08-30 10:52 UTC, Perederey requested changes
Хороший старт! Из основного

1) Добавить сохранение в "базе данных“ map[string]string. Как вариант, например, нам нужно подсчитать количество всех сгенерированных ссылок, для этого нужно использовать «базу данных»
2) Перенести инициализацию роутера
3) Вместо `internal/app/handlers` сделать `internal/handlers`
4) Не увидел использования context совсем и Middleware, добавь пожалуйста. Например с помощью context ты можешь делать отмену заказа действия, а с помощью middlware логировать вызов хендлера
6) Разделить логику функцию Fold и Unflod  - лучше в них добавить зависимостью сервис который будет генерировать ссылку или получать такую же по схеме. Заодно ты проработаешь тему с зависимостями в функциях ;)

Удачи!

2021-08-30 10:52 UTC, Perederey commented on cmd/shortener/main.go
> +	router := gin.Default()
лучше вынести это из main в `internal/router` например тогда и для теста не надо будет объявлять отдельно, а просто использовать зависимость

2021-08-30 10:52 UTC, Perederey commented on internal/app/handler_test.go
> +			assert.Equal(t, tt.want.code, w.Code)
тут бы еще добавить проверку body (json) и заголовков, добавь пожалуйста

2021-08-30 10:52 UTC, Perederey commented on internal/app/handler_test.go
> +			assert.Equal(t, tt.want.code, w.Code)
тоже самое, добавить лучше еще проверку body, что ты отдаешь нужные данные

2021-08-30 10:52 UTC, Perederey commented on internal/app/handler_test.go
> +package app
обычно в app все не складывают, лучше просто internal/handlers, internal/repo и так далее

2021-08-30 11:54 UTC, khodya commented on cmd/shortener/main.go
> +	router := gin.Default()
Исправил. Перенес тесты в router_test, чтобы не было циклических зависимостей

2021-08-30 11:57 UTC, khodya commented on internal/app/handler_test.go
> +package app
переименовал в handlers

2021-08-30 12:22 UTC, khodya commented on internal/app/handler_test.go
> +			assert.Equal(t, tt.want.code, w.Code)
по заголовкам требований нет, как и по body, непонятно что проверять

2021-08-30 12:29 UTC, khodya commented
### Спасибо за фидбэк!

> 1. Добавить сохранение в "базе данных“ map[string]string. Как вариант, например, нам нужно подсчитать количество всех сгенерированных ссылок, для этого нужно использовать «базу данных»

в требованиях к инкременту ничего такого нет, предлагаю сделать это в следующих спринтах!

> 2. Перенести инициализацию роутера

Сделано!

> 3. Вместо internal/app/handlers сделать internal/handlers

Сделано!

> 4. Не увидел использования context совсем и Middleware, добавь пожалуйста. Например с помощью context ты можешь делать отмену заказа действия, а с помощью middlware логировать вызов хендлера

Предлагаю сделать это, когда добавятся слои в приложении (db, intermediate И так далее)

> 5. Разделить логику функцию Fold и Unflod - лучше в них добавить зависимостью сервис который будет генерировать ссылку или получать такую же по схеме. Заодно ты проработаешь тему с зависимостями в функциях ;)

То же самое. Предлагаю сделать это в последующих спринтах, когда добавятся слои.



_Спасибо за подробный фидбэк! Думаю, что многие комментарии можно было бы вынести в изначальные требования к инкрементам. _

2021-08-31 11:47 UTC, khodya commented
@Perederey

2021-08-31 12:52 UTC, Perederey commented
> Спасибо за фидбэк!

Добавить сохранение в "базе данных“ map[string]string. Как вариант, например, нам нужно подсчитать количество всех сгенерированных ссылок, для этого нужно использовать «базу данных»
в требованиях к инкременту ничего такого нет, предлагаю сделать это в следующих спринтах!

Перенести инициализацию роутера
Сделано! 👍 

> Вместо internal/app/handlers сделать internal/handlers
Сделано! 👍 
 
Не увидел использования context совсем и Middleware, добавь пожалуйста. Например с помощью context ты можешь делать отмену заказа действия, а с помощью middlware логировать вызов хендлера
Предлагаю сделать это, когда добавятся слои в приложении (db, intermediate И так далее)

Не, давай все же сделаем тут - про Middleware было в уроке 2.3, надо закрепить тему 

Разделить логику функцию Fold и Unflod - лучше в них добавить зависимостью сервис который будет генерировать ссылку или получать такую же по схеме. Заодно ты проработаешь тему с зависимостями в функциях ;)

То же самое. Предлагаю сделать это в последующих спринтах, когда добавятся слои.
Договорились 👍 

@Perederey
Спасибо за подробный фидбэк! Постараюсь все воплотить в реальность в течение курса) Думаю, что многие комментарии можно было бы вынести в изначальные требования к инкрементам. 

Возможно, но мы же не хотим, чтобы студенты решали задачи как роботы, это тоже важная штука ;)

2021-08-31 12:54 UTC, Perederey commented
автотесты не пройдены, надо их сдать.

2021-08-31 12:55 UTC, Perederey reviewed
Почти запрувил, но в следующих инкрементах будет сложнее, лучше, конечно сделать Middleware в этом инкременте.

Давай разберемся с автотестами, что-то там красным они горят.

2021-08-31 12:58 UTC, khodya commented
автотесты для первых трех инкрементов прошли
<img width="681" alt="Screenshot 2021-08-31 at 15 55 45" src="https://user-images.githubusercontent.com/3818729/131506451-337c028a-7b6d-43cf-b8e0-bf0ce740d51e.png">
а другие падают вроде как это норма https://yandex-students.slack.com/archives/C02AJRGPG3V/p1629374196080100

2021-08-31 13:11 UTC, khodya commented
@Perederey

2021-08-31 13:58 UTC, Perederey commented
Да, я не увидел сразу, что это другой инкремент. Хорошо, я тебя заапрувлю, но обрати внимание, пожалуйста, на мои комментарии — а то правда, потом много придется делать ;)

2021-08-31 13:59 UTC, Perederey approved these changes

2021-08-31 15:06 UTC, merged