Sprint 2 changes
khodya/go-urlshortener pull request #2
Opened 2021-09-14 22:07 UTC by khodya

all tests passed

2021-09-15 07:40 UTC, Perederey requested changes
В целом хорошо!

Основные моменты
Надо немного работу,
1)  добавить где надо возвращение ошибок. 
2) Добавить фабричные методы NewStorage, NewDB и так далее, а не задавать переменные. 
3) Добавить комментарии к публичным функциям
4) В тестах использовать больше специальных функций

2021-09-15 07:40 UTC, Perederey commented on cmd/shortener/main.go
> +	flag.StringVar(&serverAddress, "a", parseServerAddress(), "Server address is not specified.")
я бы конечно лучше бы все три переменных сделал бы в одном месте, в config, например

2021-09-15 07:40 UTC, Perederey commented on internal/handlers/handlers.go
> +		baseURL, _ = url.Parse(DefaultBaseURL)
Лучше бы делать проверку на ошибку. А что если url будет неправильный. Если не хочешь в функции вызвать error, то тогда тут можно прямо вызвать Panic

2021-09-15 07:40 UTC, Perederey commented on internal/handlers/handlers.go
> +	return *baseURL
лучше тогда может быть вернуть поинтер в функции?

2021-09-15 07:40 UTC, Perederey commented on internal/handlers/handlers.go
> +		c.JSON(http.StatusBadRequest, struct{}{})
немного странно возвращать пустую структуру? Может быть тут переделать? например функция может принимать поинтер, и тогда сюда можно передавать nil

Либо же сделать для ошибок другую функцию c.Error() и не мучаться
Либо передавать саму ошибку.

2021-09-15 07:40 UTC, Perederey commented on internal/router/router_test.go
> +			assert.Nil(t, json.Unmarshal(w.Body.Bytes(), &js))
есть функция для сравнения двух json

assert.JSONEq()

2021-09-15 07:40 UTC, Perederey commented on internal/shortener/shortener_test.go
> +	assert.Nil(t, err)
а тут лучше

```go
require.NoError(t, err)
```

Тогда ты не будешь проверять тест дальше, если будет ошибка и эта более правильная функция для проверок ошибок.

2021-09-15 07:40 UTC, Perederey commented on internal/storage/storage.go
> +var db DB
я бы лучше их передавал бы в зависимость

сделал бы две функции

NewDB()
NewFileStore()

и где-нибудь в main.go их создавал.

2021-09-15 07:40 UTC, Perederey commented on internal/storage/storage.go
> +	db, _ = fileStore.LoadFromDisk()
лучше всегда проверять на ошибки.

2021-09-15 07:40 UTC, Perederey commented on internal/storage/storage.go
> +	fileStore.SaveOnDisk(db)
тут же тоже может быть ошибка? Надо добавить

2021-09-15 08:27 UTC, khodya commented on internal/handlers/handlers.go
> +		baseURL, _ = url.Parse(DefaultBaseURL)
Если url будет неправильный, то используется `DefaultBaseUrl` который всегда правильный (это константа)

2021-09-15 08:28 UTC, khodya commented on internal/router/router_test.go
> +			assert.Nil(t, json.Unmarshal(w.Body.Bytes(), &js))
здесь цель была проверить, что response body - это валидный json, JSONEq здесь не очень подходит, но может есть способы проверить валидность json проще?

2021-09-15 08:30 UTC, khodya commented on internal/storage/storage.go
> +var db DB
по идее main.go не должен ничего знать про storage, он ведь напрямую их не использует, верно?

2021-09-15 08:36 UTC, khodya commented on internal/storage/storage.go
> +	db, _ = fileStore.LoadFromDisk()
а что мы будем с ней делать? я бы залогировал, что не удалось прочитать базу, но предлагаю сделать это в теме логгирование

2021-09-15 08:38 UTC, khodya commented on internal/storage/storage.go
> +var db DB
по поводу фабричных методов - согласен

2021-09-15 08:42 UTC, khodya commented on internal/storage/storage.go
> +	fileStore.SaveOnDisk(db)
предлагаю сделать это в уроке логгирование

2021-09-15 09:40 UTC, khodya commented on internal/handlers/handlers.go
> +		c.JSON(http.StatusBadRequest, struct{}{})
Исправил!

2021-09-15 09:42 UTC, khodya commented on cmd/shortener/main.go
> +	flag.StringVar(&serverAddress, "a", parseServerAddress(), "Server address is not specified.")
а с другой стороны не нужно будет тянуть лишнюю зависимость из config, мне кажется в данном случае чем проще тем лучше

2021-09-15 09:45 UTC, khodya commented on internal/handlers/handlers.go
> +	return *baseURL
идея в том чтобы глобальный baseURL не был поинтером, чтобы не было риска случайно передать его в функцию "по ссылке"

2021-09-15 09:46 UTC, khodya commented on internal/shortener/shortener_test.go
> +	assert.Nil(t, err)
спасибо!

2021-09-15 09:49 UTC, khodya commented on internal/storage/storage.go
> +var db DB
но почему здесь нельзя использовать standalone базу? по сути экземпляр создается один раз внутри пакета `storage`, мы предоставляем клиенту `Put` `Get` операции... пусть вся это логика остается внутри `storage` на мой взгляд.

2021-09-15 10:06 UTC, khodya commented
Спасибо за ревью!

- Комментарии к публичным методам обязательно добавлю, предлагаю не блокироваться сейчас на это)

- Фабрики NewStorage, NewDB  - я согласен, что это общепринятый паттерн, но нужен ли он здесь? Идея заключалась в том, чтобы вся логика оставалась внутри пакета `storage`, а не делегировалась кому-то еще.

- Спасибо полезные функции в тестах! Вопрос про проверку json пока остается для меня открытым.

- По поводу обработки ошибок - я старался написать приложение так, чтобы оно не валилось из-за ошибок парсинга, записи/чтения в файл, но все эти случаи необходимо логировать. Предлагаю сделать это в уроке логирование.

2021-09-15 16:58 UTC, khodya commented
@Perederey

2021-09-16 09:50 UTC, khodya commented
@Perederey Саша, нужен твой фидбэк, пожалуйста :)

2021-09-17 05:56 UTC, Perederey approved these changes
Хорошо, давай двигаться дальше ;)

2021-09-17 07:03 UTC, merged